name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          use-poetry: true  # Install Poetry using the official action

      - name: Build the application
        run: poetry build

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/find-a-number-game  # Static project URL

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: .  # Download artifacts to the current directory

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/  # Use the downloaded artifacts
